---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: kube-system
automountServiceAccountToken: true

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: kube-system-dashboard-user
subjects:
  - kind: ServiceAccount
    name: dashboard-sa
    namespace: kube-system
roleRef:
  kind: Role
  namespace: kube-system
  name: cluster-admin
  apiVersion: rbac.authorization.k8s.io/v1alpha1
