---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: kube-system
automountServiceAccountToken: true

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-system-dashboard-user
subjects:
  - kind: ServiceAccount
    name: dashboard-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
