---
apiVersion: v1
kind: Service
metadata:
  name: studentbook
spec:
  ports:
  - port: 8000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: studentbook
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: studentbook
  name: studentbook
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: studentbook
    spec:
      initContainers:
      - image: faraazkhan/iacc-demo-app
        name: studentbook-migrations
        command: ['sh', '-c', 'bundle exec rake db:migrate']
        env:
        - name: DATABASE_URL
          value: "mysql2://mysql.default.svc.cluster.local:3306/student_development"
        - name: REDIS_URL
          value: "redis://redis.default.svc.cluster.local:6379/0"
      containers:
      - image: faraazkhan/iacc-demo-app
        name: studentbook
        env:
        - name: DATABASE_URL
          value: "mysql2://mysql.default.svc.cluster.local:3306/student_development"
        - name: REDIS_URL
          value: "redis://redis.default.svc.cluster.local:6379/0"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: studentbook
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
